name: queryfunc
channels:
        - pyviz
packages:
        - jupyter_panel_proxy
dependencies:
        langchain==0.0.332
        openai==0.28.1
        panel==1.3.1
        param==2.0.1
        python-dotenv==1.0.0
